- name: install and start apache on webservers
  hosts: webservers
  become: true
  tasks:

    - name: install apache
      package:
        name: apache2
        state: present

    - name: start apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: deploy index.html
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      notify: restart apache
